Deduplication is fixed
evolution-gaming/kafka-journal pull request #501
Opened 2023-07-26 10:47 UTC by DeviLab

2023-07-27 14:58 UTC, dfakhritdinov requested changes

2023-07-27 14:58 UTC, dfakhritdinov commented on journal/src/main/scala/com/evolutiongaming/kafka/journal/Journals.scala
> +            stream.map(Option(_)).concat(Stream.single(empty)).stateful(empty) {
Existing implementation skips all events with `seqNr` less than `from` (line 271) while new one process full stream from the beginning, if I'm not missing anything

2023-07-27 16:45 UTC, dfakhritdinov commented
Thanks for the fix, LGTM

2023-08-01 13:05 UTC, dfakhritdinov approved these changes

2023-08-01 14:52 UTC, theide approved these changes

2023-08-01 15:51 UTC, merged